---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Effective Pest Treament That Protects Pollinators"
subtitle: "https://github.com/shivanikuckreja/CitrolaKuckrejaSaltman_ENV872_EDA_FinalProject/tree/main/Project"
author: "Sam Saltman, Shivani Kuckreja, Jessica Citrola"
fontsize: 12pt
mainfont: Times New Roman

---

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
getwd()
# Load your packages

library(tidyverse)
library(lubridate)
library(knitr)
library(ggplot2)
library(RColorBrewer)


# Set your ggplot theme
mytheme <- theme_classic() +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

# Load your datasets

Original_ECOTOX_CSV <- read.csv("../Data/Raw/ECOTOX_Neonicotinoids_Insects_raw.csv", stringsAsFactors = TRUE)
```


# Rationale and Research Questions

**Pollination is a critical component of agriculture. Honeybees are important pollinators. Our research looks to see if there are exposure methods and chemicals that do not cause significant harm to honeybees while eliminating pests. The goal of our research is to determine potential treatment methods that reduce pests while having little to no impact on pollinators.**

Questions:

1.   _Is there an exposure type that has less impact on bees than non-bee insects?_

2.   _Are there chemicals that have a high mortality rate for non-bee insects and low rate for bees?_
  

\newpage

# Dataset Information



\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: Is there an exposure type that has less impact on bees than non-bee insects?

## Question 2: Are there chemicals that have a high mortality rate for non-bee insects and low rate for bees?




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
